// Temporary AWS configuration for local development
// This file would normally be generated by Amplify CLI

const awsconfig = {
  aws_project_region: process.env.REACT_APP_AWS_REGION || 'ap-southeast-1',
  aws_cognito_region: process.env.REACT_APP_AWS_REGION || 'ap-southeast-1',
  aws_user_pools_id: 'demo-user-pool-id',
  aws_user_pools_web_client_id: 'demo-client-id',
  oauth: {},
  aws_cognito_username_attributes: ['email'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['email'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: []
  },
  aws_cognito_verification_mechanisms: ['email']
};

export default awsconfig;
